{% set name = "roboticstoolbox-python" %}
{% set version = "0.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/roboticstoolbox-python-{{ version }}.tar.gz
  sha256: 4a63590786015011e4a637226d41b397d9c1a7d95004135a6a216645b6d2f0d1

build:
  number: 0
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - ansitable
    - matplotlib-base
    - numpy >=1.18.0
    - pgraph-python
    - python
    - qpsolvers
    - rtb-data
    - scipy
    - spatialmath-python >=0.9.2
    - swift-sim >=0.8.1
    - sympy
    - bullet
    - imageio
    - imageio-ffmpeg
    - vpython                                # [not aarch64]
    - numpy-stl
    - pyyaml

test:
  imports:
    - roboticstoolbox
    - roboticstoolbox.backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/petercorke/robotics-toolbox-python
  summary: A Python library for robotic education and research
  dev_url: https://github.com/petercorke/roboticstoolbox-python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - petercorke
    - jhavl
